In [61]:
import pandas as pd
import math

In [62]:
kandidat = pd.read_csv("kandidatgudang.csv")
kandidat

LT          BT
0 -7.132744  111.735032
1 -6.910365  112.077296
2 -7.108972  112.402401
3 -7.122210  112.163826
4 -7.168514  111.874091
5 -7.094069  111.911792
6 -6.883889  112.023353
7 -6.879670  112.033777
8 -6.971084  112.252429
9 -7.195150  112.383633

In [63]:
titik_d = pd.read_csv("titikdistribusi.csv")
titik_d

Pagu        LT          BT
0      1560 -6.783554  111.781803
1      7300 -6.772281  111.725225
2       670 -6.879302  112.020210
3      1460 -6.770554  111.735667
4      5940 -6.769738  111.719349
...     ...       ...         ...
1224   2030 -6.981347  112.285230
1225   1770 -6.978877  112.301108
1226    470 -7.014812  112.254595
1227   2030 -7.025433  112.232147
1228   1770 -6.989497  112.303315

[1229 rows x 3 columns]

In [64]:
titik_d['Pagu'] = titik_d['Pagu'].astype(float)

In [65]:
for i in titik_d["LT"]:
  print(i)

-6.78355361013266
-6.77228108720044
-6.87930232876153
-6.77055419333396
-6.76973751004239
-6.77115876836813
-6.81235387639841
-6.7877123971636
-6.811390618481
-6.82256870531328
-6.77199681499647
-6.80548783665792
-6.80763264129888
-6.82123607745948
-6.80888630133742
-6.7957647415561
-6.79519491277554
-6.89324123210692
-6.81909976639513
-6.76605376995013
-6.8083834542483
-6.8026884310812
-6.77991804801631
-6.7779526
-6.96236968621309
-6.95617479207485
-6.99348551126969
-6.98169724255746
-6.97685375745411
-6.93403063236743
-6.95668104368909
-6.97543640200128
-6.90707560249353
-6.9839162052221
-6.91248154933089
-6.90159150917368
-6.96658674967293
-6.97700367156331
-7.04855289553911
-7.01746007433981
-7.00547017886138
-6.99610188286545
-7.01569565526213
-7.01807784582883
-7.01507507445067
-7.0368659
-7.02445504339835
-7.00193777717985
-7.00092861504678
-6.8288653010823
-6.84477610835522
-6.88406472226359
-6.90209661063382
-6.87724653801304
-7.00505057220128
-6.87602458435118
-6.86480485176

In [66]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot
%matplotlib inline 

In [67]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [68]:
def initilization_of_population(size,n_feat):
    population = []
    for i in range(size):
        chromosome = np.ones(n_feat,dtype=np.bool)
        chromosome[:int(0.3*n_feat)]=False
        np.random.shuffle(chromosome)
        population.append(chromosome)
    return population

In [69]:
def selection(pop_after_fit,n_parents):
    population_nextgen = []
    for i in range(n_parents):
        population_nextgen.append(pop_after_fit[i])
    return population_nextgen

In [70]:
def crossover(pop_after_sel):
    population_nextgen=pop_after_sel
    for i in range(len(pop_after_sel)):
        child=pop_after_sel[i]
        child[3:7]=pop_after_sel[(i+1)%len(pop_after_sel)][3:7]
        population_nextgen.append(child)
    return population_nextgen

In [71]:
def dist_func(x1,x2,y1,y2,pag):
  dist = math.sqrt(((x1-x2)**2)+((y1-y2)**2))
  res = dist*111.319
  final_res = res*pag
  return final_res

**Sample untuk 1 populasi**

In [72]:
rand_titik = titik_d.sample()
rand_gud = kandidat.sample()

In [73]:
rand_titik

Pagu        LT          BT
206  6340.0 -7.069672  111.975438

In [74]:
rand_gud


LT          BT
8 -6.971084  112.252429

In [75]:
type(rand_titik["LT"])

pandas.core.series.Series

In [76]:
for i in titik_d.sample():
  print(i)

Pagu
LT
BT


In [77]:
func_list = []
x1 = rand_titik.iloc[0]["LT"]
x2 = rand_gud.iloc[0]["LT"]
y1 = rand_titik.iloc[0]["BT"]
y2 = rand_gud.iloc[0]["BT"]
pag = rand_titik.iloc[0]["Pagu"]
func_list.append(x1)
func_list.append(x2)
func_list.append(y1)
func_list.append(y2)
func_list.append(pag)
dist_func(x1,x2,y1,y2,pag)

207503.21214120815

**Sample untuk n populasi**

In [78]:
#n itu jumlah populasi yang mau di inuput
rand_titik_mul = titik_d.sample()
rand_gud = kandidat.sample()

In [79]:

sel_list = []
for i in range(1229):
  #rand_titik_mul = titik_d.sample(n=i)
  
  rand_gud = kandidat.sample(n=10)
  x1_mul = titik_d.iloc[0]["LT"]
  x2 = rand_gud.iloc[0]["LT"]
  y1_mul = titik_d.iloc[0]["BT"]
  y2 = rand_gud.iloc[0]["BT"]
  pag_mul = titik_d.iloc[0]["Pagu"]
  sel_list.append(dist_func(x1_mul,x2,y1_mul,y2,pag_mul))

print(titik_d)
print(rand_gud)  
print(sel_list)
#sel_list.sort()

        Pagu        LT          BT
0     1560.0 -6.783554  111.781803
1     7300.0 -6.772281  111.725225
2      670.0 -6.879302  112.020210
3     1460.0 -6.770554  111.735667
4     5940.0 -6.769738  111.719349
...      ...       ...         ...
1224  2030.0 -6.981347  112.285230
1225  1770.0 -6.978877  112.301108
1226   470.0 -7.014812  112.254595
1227  2030.0 -7.025433  112.232147
1228  1770.0 -6.989497  112.303315

[1229 rows x 3 columns]
         LT          BT
1 -6.910365  112.077296
9 -7.195150  112.383633
8 -6.971084  112.252429
5 -7.094069  111.911792
2 -7.108972  112.402401
0 -7.132744  111.735032
7 -6.879670  112.033777
3 -7.122210  112.163826
6 -6.883889  112.023353
4 -7.168514  111.874091
[121689.18788439895, 55840.44239284623, 68745.536170318, 58457.70871498428, 46832.71292746806, 126616.64224720476, 87977.23364113597, 87977.23364113597, 46832.71292746806, 88655.61484876704, 46832.71292746806, 126616.64224720476, 87977.23364113597, 45422.03423608268, 55840.44239284623, 6874

In [80]:
print(len(sel_list))

1229


In [81]:
gud_mul = pd.concat([kandidat]*123)
gud_mul

LT          BT
0  -7.132744  111.735032
1  -6.910365  112.077296
2  -7.108972  112.402401
3  -7.122210  112.163826
4  -7.168514  111.874091
..       ...         ...
5  -7.094069  111.911792
6  -6.883889  112.023353
7  -6.879670  112.033777
8  -6.971084  112.252429
9  -7.195150  112.383633

[1230 rows x 2 columns]

In [82]:
gud_mul_new = gud_mul.iloc[:-1 , :]
gud_mul_new

LT          BT
0  -7.132744  111.735032
1  -6.910365  112.077296
2  -7.108972  112.402401
3  -7.122210  112.163826
4  -7.168514  111.874091
..       ...         ...
4  -7.168514  111.874091
5  -7.094069  111.911792
6  -6.883889  112.023353
7  -6.879670  112.033777
8  -6.971084  112.252429

[1229 rows x 2 columns]

In [83]:
rand_gud_new = gud_mul_new.sample(1229)
rand_gud_new

LT          BT
1  -6.910365  112.077296
2  -7.108972  112.402401
8  -6.971084  112.252429
9  -7.195150  112.383633
8  -6.971084  112.252429
..       ...         ...
2  -7.108972  112.402401
1  -6.910365  112.077296
8  -6.971084  112.252429
3  -7.122210  112.163826
4  -7.168514  111.874091

[1229 rows x 2 columns]

In [84]:
#mencari titik dengan fitness terbaik dan terburuk
def minimum(sel_list, n):
 
    
    minpos = sel_list.index(min(sel_list))
 
   
    maxpos = sel_list.index(max(sel_list))
 
    
    print ("Fitness terburuk berada di posisi", maxpos + 1)
    print ("Fitness terbaik berada di posisi", minpos + 1)
 
 

minimum(sel_list, len(sel_list))

Fitness terburuk berada di posisi 6
Fitness terbaik berada di posisi 14


In [85]:
#nilai fitness terbaik
min(sel_list)

45422.03423608268

In [86]:
#titik distribusi ke gudang dengan menggunakan array
arr = rand_gud.to_numpy()

In [87]:
arr

array([[ -6.910365  , 112.077296  ],
       [ -7.19515   , 112.3836325 ],
       [ -6.9710842 , 112.2524289 ],
       [ -7.0940691 , 111.9117923 ],
       [ -7.108972  , 112.4024008 ],
       [ -7.13274413, 111.73503239],
       [ -6.8796702 , 112.0337771 ],
       [ -7.1222099 , 112.1638263 ],
       [ -6.8838892 , 112.0233535 ],
       [ -7.1685139 , 111.8740913 ]])

In [88]:
list_1 = arr.tolist()
list_1

[[-6.910365, 112.077296],
 [-7.19515, 112.3836325],
 [-6.9710842, 112.2524289],
 [-7.0940691, 111.9117923],
 [-7.108972, 112.4024008],
 [-7.1327441272, 111.735032394],
 [-6.8796702, 112.0337771],
 [-7.1222099, 112.1638263],
 [-6.8838892, 112.0233535],
 [-7.1685139, 111.8740913]]

In [89]:
len(arr)

10

In [90]:
arr[0]

array([ -6.910365, 112.077296])

In [91]:
arr1 = rand_titik_mul.to_numpy()

In [92]:
arr1

array([[1880.        ,   -6.99529131,  112.41892467]])

In [93]:
len(arr1)

1

In [94]:
arr1[0]

array([1880.        ,   -6.99529131,  112.41892467])

In [95]:
titik_d_new = titik_d.drop(columns =['Pagu'])
titik_d_new

LT          BT
0    -6.783554  111.781803
1    -6.772281  111.725225
2    -6.879302  112.020210
3    -6.770554  111.735667
4    -6.769738  111.719349
...        ...         ...
1224 -6.981347  112.285230
1225 -6.978877  112.301108
1226 -7.014812  112.254595
1227 -7.025433  112.232147
1228 -6.989497  112.303315

[1229 rows x 2 columns]

In [96]:
titik_arr = titik_d_new.to_numpy()

In [97]:
titik_arr

array([[ -6.78355361, 111.78180261],
       [ -6.77228109, 111.72522465],
       [ -6.87930233, 112.02020956],
       ...,
       [ -7.01481242, 112.25459451],
       [ -7.02543289, 112.23214664],
       [ -6.98949733, 112.30331474]])

In [98]:
len(titik_arr)

1229

In [99]:
#titik_list = titik_arr.tolist()
#titik_list

In [100]:
gud_arr = rand_gud_new.to_numpy()
gud_arr

array([[ -6.910365 , 112.077296 ],
       [ -7.108972 , 112.4024008],
       [ -6.9710842, 112.2524289],
       ...,
       [ -6.9710842, 112.2524289],
       [ -7.1222099, 112.1638263],
       [ -7.1685139, 111.8740913]])

In [101]:
gud_list = gud_arr.tolist()
gud_list

[[-6.910365, 112.077296],
 [-7.108972, 112.4024008],
 [-6.9710842, 112.2524289],
 [-7.19515, 112.3836325],
 [-6.9710842, 112.2524289],
 [-6.910365, 112.077296],
 [-7.108972, 112.4024008],
 [-7.1685139, 111.8740913],
 [-7.1685139, 111.8740913],
 [-7.108972, 112.4024008],
 [-6.910365, 112.077296],
 [-7.1685139, 111.8740913],
 [-7.0940691, 111.9117923],
 [-7.108972, 112.4024008],
 [-7.1327441272, 111.735032394],
 [-7.19515, 112.3836325],
 [-6.910365, 112.077296],
 [-7.1685139, 111.8740913],
 [-7.1327441272, 111.735032394],
 [-7.0940691, 111.9117923],
 [-7.0940691, 111.9117923],
 [-7.0940691, 111.9117923],
 [-6.8796702, 112.0337771],
 [-6.8796702, 112.0337771],
 [-7.0940691, 111.9117923],
 [-7.19515, 112.3836325],
 [-6.8838892, 112.0233535],
 [-7.0940691, 111.9117923],
 [-7.108972, 112.4024008],
 [-6.9710842, 112.2524289],
 [-7.1222099, 112.1638263],
 [-7.1222099, 112.1638263],
 [-6.8838892, 112.0233535],
 [-7.1222099, 112.1638263],
 [-6.8796702, 112.0337771],
 [-6.910365, 112.077296],
 [-

# Mulai GA nya dari sini

In [102]:
kandidat = len(kandidat)
print(kandidat)

10


In [103]:
def initPopulasi(ukuranPopulasi,kandidat):
  P = np.empty((ukuranPopulasi,kandidat))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    for j in range(kandidat):
        I = np.random.randint(2)
        P[i][j]=I
  return P

ukuranPopulasi = 4
P = initPopulasi (ukuranPopulasi,kandidat)
print(P)

[[0 0 1 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 1 1]
 [1 0 0 0 1 0 0 0 0 0]]


In [104]:
len(P)

4

In [105]:
sz = P.shape
print(sz)

(4, 10)


In [106]:
jumlahGudang = len(list_1) 
jumlahGudang

10

In [107]:
n = len(gud_list) 
n

1229

In [108]:
import numpy as np 
import random
from array import *

In [109]:
n = len(gud_list) 
sz = P.shape
ukuranPopulasi = sz[0]
jumlahKota = sz[1]
jumlahGudang = len(list_1) 

#koordinat gudang = list_1
#koordinat titikdist = gud_list

matrikJarak = np.zeros((ukuranPopulasi,), dtype=float)
#matrikJarak = np.empty((ukuranPopulasi))
#matrikJarak  = matrikJarak.astype('float')

print(ukuranPopulasi)
print(jumlahKota)
print(jumlahGudang)
print(n)
for i in range(ukuranPopulasi):  #berulang sebanyak jumlah populasi
    print('#########################################################################################################')
    #jarak = np.empty((jumlahGudang))
    jarak = np.zeros((jumlahGudang,), dtype=float)
    #jarak = jarak.astype('float')
    print(f'jarak = {jarak}')
    for j in range(n): #jumlah titik distribusi
        #print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        jarakTerkecil = 0
        for k in range(jumlahGudang): #jumlah gudang
            #print(f'P[i][k] =1 = {P[i][k]==1}')
            if(P[i][k]==1):
                #print(f'jarak terkecil = {jarakTerkecil}')
                #print(f'menghitung jarak pada k = {k} dengan jarak[k] = {jarak[k]}' )
                jrkX = list_1[k][0]-gud_list[j][0]
                jrkY = list_1[k][1]-gud_list[j][1]
                d = np.sqrt(jrkX**2 + jrkY**2 )
                if jarakTerkecil == 0:
                    jarakTerkecil = d
                else:
                    if jarakTerkecil > d:
                        jarakTerkecil = d
                jarak[k] = jarak[k] + jarakTerkecil
            #print(f'jarak[k] = {jarak[k]}')
        #print(jarakTerkecil)
    print(jarak)
    for l in range(jumlahGudang):
        matrikJarak[i] = matrikJarak[i] + jarak[l]
print(f'matrikJarak = {matrikJarak}')
        

4
10
10
1229
#########################################################################################################
jarak = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.           0.         324.09131501   0.         303.1737677
   0.           0.           0.         236.00884153   0.        ]
#########################################################################################################
jarak = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.           0.         324.09131501   0.           0.
   0.           0.           0.         232.85160642   0.        ]
#########################################################################################################
jarak = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.           0.         324.09131501 236.56643414   0.
   0.           0.           0.         178.99428202 184.66209606]
#########################################################################################################
jarak = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[283.80154364   0.   

In [110]:
'''for j in range(jumlahGudang): #jumlah gudang
        if (P[i][j]]=1):
            for k in range(n): #jumlah titik distribusi
                jrkX = list_1[j][0]-gud_list[k][0]
                jrkY = list_1[j][1]-gud_list[k][1]
                d = np.sqrt(jrkX**2 + jrkY**2 )
                jarak = jarak  + d
                print(f'jaraknya = {jarak}')'''
                
        
'''print('##########################################################################')
    print(f'iterasi i ke-{i}')
    jarak = 0
    for j in range(jumlahKota-1):
        print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        print(f'iterasi j ke-{j}')
        print (f'i = {i}')
        print (f'j = {j}')
        print (f'P[i][j] = {P[i][j]}')
        print (f'P[i][j+1] = {P[i][j+1]}')
        print (f'gud_list[P[i][j]][0] = {gud_list[P[i][j]][0]}')
        print (f'gud_list[P[i][j+1]][0] = {gud_list[P[i][j]+1][0]}')
        jrkX = gud_list[P[i][j]][0]-gud_list[P[i][j+1]][0]
        print(f'jrkX = {jrkX}')
        jrkY = gud_list[P[i][j]][1]-gud_list[P[i][j+1]][1]
        print(f'jrkY = {jrkY}')
        d = np.sqrt(jrkX**2 + jrkY**2 )   
        jarak = jarak  + d
        res = jarak*111.319
        print(f'jaraknya = {jarak}')'''
        
    
       
'''dn =  np.sqrt((gud_list[P[i][jumlahKota-1]][0]-gud_list[P[i][0]][0])**2+ (gud_list[P[i][jumlahKota-1]][1]-gud_list[P[i][0]][1])**2 )
    print (f'dn = {dn}')
    jarak = jarak  + dn
    print (f'jarak = {jarak}')
    res = jarak*111.319
    matrikJarak[i] = res
    print (f'matrikJarak[i] = {matrikJarak[i]}')'''
    
    

'''print (f'matrikJarak = {matrikJarak}')
        
        
print(P[i][j+2])'''

"print (f'matrikJarak = {matrikJarak}')\n        \n        \nprint(P[i][j+2])"

In [111]:
n = len(list_distrib)
print(n)

NameError: name 'list_distrib' is not defined

In [ ]:
sz = populasi.shape
sz

NameError: name 'populasi' is not defined

In [ ]:
def fungsiObjectif(populasi,gud_list,list_1):
    n = len(gud_list)
    sz = P.shape
    ukuranPopulasi = sz[0]
    jumlahGudang = sz[1]

    matrikJarak = np.zeros((ukuranPopulasi,), dtype=float)
    
    for i in range(ukuranPopulasi):  #berulang sebanyak jumlah populasi
        #print('#########################################################################################################')
        #jarak = np.empty((jumlahGudang))
        jarak = np.zeros((jumlahGudang,), dtype=float)
        #jarak = jarak.astype('float')
        #print(f'jarak = {jarak}')
        for j in range(n): #jumlah titik distribusi
            #print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
            jarakTerkecil = 0
            for k in range(jumlahGudang): #jumlah gudang
                #print(f'P[i][k] =1 = {P[i][k]==1}')
                if(P[i][k]==1):
                    #print(f'jarak terkecil = {jarakTerkecil}')
                    #print(f'menghitung jarak pada k = {k} dengan jarak[k] = {jarak[k]}' )
                    jrkX = gud_list[k][0]-list_1[j][0]
                    jrkY = gud_list[k][1]-list_1[j][1]
                    d = np.sqrt(jrkX**2 + jrkY**2 )
                    if jarakTerkecil == 0:
                        jarakTerkecil = d
                    else:
                        if jarakTerkecil > d:
                            jarakTerkecil = d
                    jarak[k] = jarak[k] + jarakTerkecil
                #print(f'jarak[k] = {jarak[k]}')
            #print(jarakTerkecil)
        #print(jarak)
        for l in range(jumlahGudang):
            matrikJarak[i] = matrikJarak[i] + (jarak[l]*111.319)
    #print(f'matrikJarak = {matrikJarak}')
    return matrikJarak
'''
  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = gud_list[populasi[i][j]][0]-gud_list[populasi[i][j+1]][0]
      jrkY = gud_list[populasi[i][j]][1]-gud_list[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      res = jarak*111.319
      print(jarak)
      
    dn =  np.sqrt((gud_list[populasi[i][jumlahKota-1]][0]-gud_list[populasi[i][0]][0])**2+ (gud_list[populasi[i][jumlahKota-1]][1]-gud_list[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    res = jarak*111.319
    matrikJarak[i] = res

  return matrikJarak
'''
fitP = fungsiObjectif(P,list_1,gud_list)
print(fitP)


[ 905.81074212 1047.72515223  788.40143823  774.74255027]


In [ ]:
len(fitP)

NameError: name 'fitP' is not defined

In [ ]:
def seleksi (P,fungsiObjectif):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  Induk = np.empty((jmlInduk,jumlahKota))
  Induk = Induk.astype('int')
  
  for i in range (2):
    
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fungsiObjectif[r1] < fungsiObjectif [r2]:
      for j in range(jumlahKota):
        Induk [i][j] = P[j][r1]
    else:
      for j in range(jumlahKota):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

NameError: name 'fitP' is not defined

In [ ]:
#crossover 

def OrderXO(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]
 

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 

    Anak [0][i0] = Induk[0][i0]
    Anak [1][i0] = Induk[1][i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = Induk[0][i] 
    n2 = Induk[1][i]

    
    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol-1):
        idxAda1 = 1

      if Anak [0][j1] ==n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol-1):
        idxAda2 = 1

      if Anak [1][i0]  == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      Anak[0][batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      Anak[1][batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  return Anak

AnakCX = OrderXO(Induk)
print("Anak :",AnakCX)

Anak : [[  1   1   0  -6  -6  -6  -6  -7  -7  -6]
 [  0   1   0   0   0   0 112 112 112 112]]


In [ ]:
#tahap mutasi
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)

  I1rs1 = Induk [0][r1]
  I1rs2 = Induk [0][r2]
  I2rs1 = Induk [1][r1]
  I2rs2 = Induk [1][r2] 

  Anak [0][r1] = I1rs2
  Anak [0][r2] = I1rs1
  Anak [1][r1] = I2rs2  
  Anak [1][r2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[  1   0   1   1   1   0  -7 111  -7 111]
 [  1   0   1   1   1   0   1   1   1   1]]
AnakM : [[  1   0   1   1   1  -7  -7 111   0 111]
 [  1   0   1   1   1   1   1   1   0   1]]


In [ ]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)
  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]

  return [P,fitP]

fitAnak= fungsiObjectif(AnakM,gud_list)
print(P)
print(AnakM)
print(fitP)
print(fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print(P)
print(fitP)

NameError: name 'fungsiObjectif' is not defined

In [ ]:
# Inisialisasi paramater
PCX = 0.95
Pm = 0.01
ukuranPopulasi = 1229
max_generasi = 5



P = initPopulasi (ukuranPopulasi,jumlahKota)
print("P0 :",P)

#melakukan evaluasi P
fitP = fungsiObjectif(P,gud_list)
print("fitness populasi awal:",fitP)

print("fitness terbaik awal:",fitP.min())
print("rute awal :",P[fitP.argmin()])


for i in range(max_generasi):
  print("generasi :",i)
  Induk = seleksi(P,fitP)
  print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = OrderXO(Induk)
    print("AnakXO :",Anak)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)
      print("AnakR :",Anak)

  fitAnak = fungsiObjectif(Anak,gud_list)
  print("fitAnak :",fitAnak)

  print("fitness:",fitAnak.min())

  [P, fitP]= Elitism (P,Anak,fitP,fitAnak)   
  
print("fitness populasi akhir:",fitP)
print("fitness akhir:",fitP.min())
print("rute akhir :",P[fitP.argmin()])

NameError: name 'initPopulasi' is not defined

In [ ]:
#x1_mul = titik_d["LT"]
#x2 = kandidat.iloc[0]["LT"]
#x1_mul = titik_d.iloc[0]["BT"]
#y2 = kandidat.iloc[0]["BT"]
#pag_mul = titik_d.iloc[0]["Pagu"]
#dist_func(x1_mul,x2,y1_mul,y2,pag_mul)


In [ ]:
import random
 

def findRandom():
     
   
    num = random.randint(0, 1)
 
  
    return num
 

def generateBinaryString(N):
     
    
    S = ""
 
    
    for i in range(N):
         
        
        x = findRandom()
 
        
        S += str(x)
     
    
    print(S)
 
N = 10
 
a = generateBinaryString(N)

a



Indeks [] di kandidat.iloc[0]["LT"] dan kandidat.iloc[0]["BT"] itu tergantung bilangan hasil random biner nya.

0 = A
1 = B
2 = C
3 = D 
4 = E
5 = F
6 = G
7 = H 
8 = I
9 = J

**JADI HARUS INPUT MANUAL**

In [ ]:
fit_lst_bin = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[0]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[0]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lst_bin.append(jarak)

fit_lst_bin

In [ ]:
kandidat.iloc[0]["LT"]

In [ ]:
kandidat.iloc[0]["BT"]

In [ ]:
x1_lst = []
for i in titik_d["LT"]:
  x1_lst.append(i)
  
x1_lst

In [ ]:
y1_lst = []
for i in titik_d["BT"]:
  y1_lst.append(i)
  
y1_lst

In [ ]:
x2_lst = []
for i in kandidat["LT"]:
  x2_lst.append(i)
  
x2_lst

In [ ]:
y2_lst = []
for i in kandidat["BT"]:
  y2_lst.append(i)
  
y2_lst

In [ ]:
pag_lst = []
for i in titik_d["Pagu"]:
  pag_lst.append(i)
  
pag_lst

**Perhitungan Fitness antara Titik dan Gudang**

In [ ]:
kandidat = pd.read_csv("kandidatgudang.csv")
kandidat

In [ ]:
# gudang A
fit_lstA = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[0]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[0]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstA.append(jarak)

fit_lstA


In [ ]:
print(min(fit_lstA)) # fitness terkecil gudang A

indexA = fit_lstA.index(min(fit_lstA))


print(indexA) # titik dengan fitness terkeci gudang A

In [ ]:
# gudang B
fit_lstB = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[1]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[1]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstB.append(jarak)

fit_lstB


In [ ]:
print(min(fit_lstB)) # fitness terkecil gudang B

indexB = fit_lstB.index(min(fit_lstB))


print(indexB) # titik dengan fitness terkeci gudang B

In [ ]:
# gudang C
fit_lstC = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[2]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[2]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstC.append(jarak)

fit_lstC


In [ ]:
print(min(fit_lstC)) # fitness terkecil gudang C

indexC = fit_lstC.index(min(fit_lstC))


print(indexC) # titik dengan fitness terkeci gudang C

In [ ]:
# gudang D
fit_lstD = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[2]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[3]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstD.append(jarak)

fit_lstD


In [ ]:
print(min(fit_lstD)) # fitness terkecil gudang D

indexD = fit_lstD.index(min(fit_lstD))


print(indexD) # titik dengan fitness terkeci gudang D

In [ ]:
# gudang E
fit_lstE = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[4]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[4]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstE.append(jarak)

fit_lstE

In [ ]:
print(min(fit_lstE)) # fitness terkecil gudang E

indexE = fit_lstE.index(min(fit_lstE))


print(indexE) # titik dengan fitness terkeci gudang E

In [ ]:
# gudang F
fit_lstF = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[5]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[5]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstF.append(jarak)

fit_lstF

In [ ]:
print(min(fit_lstF)) # fitness terkecil gudang F

indexF = fit_lstF.index(min(fit_lstF))


print(indexF) # titik dengan fitness terkeci gudang F

In [ ]:
# gudang G
fit_lstG = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[6]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[6]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstG.append(jarak)

fit_lstG

In [ ]:
print(min(fit_lstG)) # fitness terkecil gudang G

indexG = fit_lstG.index(min(fit_lstG))


print(indexG) # titik dengan fitness terkeci gudang G

In [ ]:
# gudang H
fit_lstH = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[7]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[7]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstH.append(jarak)

fit_lstH

In [ ]:
print(min(fit_lstH)) # fitness terkecil gudang H

indexH = fit_lstH.index(min(fit_lstH))


print(indexH) # titik dengan fitness terkeci gudang H

In [ ]:
# gudang I
fit_lstI = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[8]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[8]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstI.append(jarak)

fit_lstI

In [ ]:
print(min(fit_lstI)) # fitness terkecil gudang I

indexI = fit_lstI.index(min(fit_lstI))


print(indexI) # titik dengan fitness terkeci gudang I

In [ ]:
# gudang J
fit_lstJ = []
for i in range(1229):
  jarak = dist_func(titik_d.iloc[i]["LT"],kandidat.iloc[9]["LT"],titik_d.iloc[i]["BT"],kandidat.iloc[9]["BT"],titik_d.iloc[i]["Pagu"])
  fit_lstJ.append(jarak)

fit_lstJ

In [ ]:
print(min(fit_lstJ)) # fitness terkecil gudang J

indexJ = fit_lstJ.index(min(fit_lstJ))


print(indexJ) # titik dengan fitness terkeci gudang J

In [ ]:
# final_df itu adalah data sesuai dengan gudang terpilih
final_df = pd.DataFrame(list(zip()),
               columns =[''])
final_df

In [ ]:
#kodingan untuk mencari total fitness dengan nilai titik 
final_df +  +